#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the cutover of Settle to the homeserver, as settled in docs/handoff/hosting.md.
# Run it from the repo root on the desktop, on the `hosting` branch, with the local server stopped.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9
ENV_FILE="${ENV_FILE:-/dev/null}"   # nothing is written to a local .env in this wizard

HOMESERVER="${HOMESERVER:-homeserver}"          # the tailnet name ssh uses
HOMESERVER_IP="100.64.0.1"
ORIGIN="https://settle.example.com"
REPO="alexzfe/settle"
HOME_FOLDER="$HOME/Homes/house"
HOME_SLUG="house"
LOCAL_DATA="$HOME/.local/share/settle"

hs() { ssh -o BatchMode=yes -o ConnectTimeout=10 "$HOMESERVER" "$@"; }

banner "Settle → homeserver: the cutover"

# ─── 1 ────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checks that need nothing from you, so a problem shows up now rather than half-way."
ok=1
if [[ "$(git branch --show-current)" != "hosting" ]]; then warn "not on the hosting branch"; ok=0; fi
if [[ -n "$(git status --porcelain)" ]]; then warn "the working tree is not clean"; ok=0; fi
if ss -ltn 2>/dev/null | grep -q ':4380 '; then warn "something listens on 4380 here: stop the local Settle first"; ok=0; fi
if ! gh auth status >/dev/null 2>&1; then warn "gh is not logged in"; ok=0; fi
if ! hs true 2>/dev/null; then
  warn "ssh $HOMESERVER failed. Tailscale SSH may want a re-authentication:"
  hs true 2>&1 | sed 's/^/    /' || true
  ok=0
fi
if [[ "$ok" == 1 ]]; then
  say "${GREEN}✓${RESET} hosting branch, clean tree, port 4380 free, gh logged in, ssh to $HOMESERVER works."
else
  warn "Fix the above and re-run."; exit 1
fi
pause

# ─── 2 ────────────────────────────────────────────────────────────────────
stage "GitHub: a token for the self-hosted runner"
say "The runner on the homeserver registers itself with GitHub using a fine-grained token that"
say "may administer only the $REPO repository. It lives on the homeserver, never in GitHub secrets."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: homeserver-runner. Expiration: 1 year (GitHub's maximum for fine-grained tokens)."
step "Repository access: Only select repositories → $REPO."
step "Repository permissions → Administration: Read and write. (Metadata: Read-only is added by itself.)"
step "Generate token, then copy it."
ask_secret ACCESS_TOKEN "Paste the token (hidden):"
[[ -n "$ACCESS_TOKEN" ]] || { warn "no token, stopping"; exit 1; }
printf 'ACCESS_TOKEN=%s\n' "$ACCESS_TOKEN" | hs 'umask 077; mkdir -p /docker/github-runner; cat > /docker/github-runner/.env'
say "${GREEN}✓${RESET} written to $HOMESERVER:/docker/github-runner/.env (mode 600; gitignored there, as every .env is)."
pause

# ─── 3 ────────────────────────────────────────────────────────────────────
stage "Homeserver: start the runner"
say "Copies deploy/github-runner/compose.yaml to /docker/github-runner/ and starts it."
scp -q deploy/github-runner/compose.yaml "$HOMESERVER:/docker/github-runner/compose.yaml"
hs 'cd /docker/github-runner && docker compose up -d' 2>&1 | sed 's/^/    /'
say "Waiting for the runner to say it is listening for jobs..."
for _ in $(seq 45); do
  if hs 'docker logs github-runner 2>&1 | grep -q "Listening for Jobs"'; then break; fi
  sleep 2
done
hs 'docker logs github-runner 2>&1 | tail -n 5' | sed 's/^/    /'
open_url "https://github.com/$REPO/settings/actions/runners"
step "Check that a runner named homeserver shows as Idle, with the label homeserver."
pause "Does it? Press Enter when it does."

# ─── 4 ────────────────────────────────────────────────────────────────────
stage "GitHub: Actions settings"
say "The runner holds the homeserver's Docker socket, so no stranger's pull request may ever run on it."
open_url "https://github.com/$REPO/settings/actions"
step "Under Fork pull request workflows, choose 'Require approval for all external contributors'."
step "Under Workflow permissions, 'Read repository contents and packages permissions' is enough (the workflow asks for packages: write itself)."
step "Save if anything changed."
pause

# ─── 5 ────────────────────────────────────────────────────────────────────
stage "Nginx Proxy Manager: settle.example.com"
say "One proxy host, like the other thirty-two: the name already resolves to this box everywhere."
open_url "http://$HOMESERVER_IP:81"
step "Hosts → Proxy Hosts → Add Proxy Host."
step "Details: Domain Names settle.example.com · Scheme http · Forward Hostname $HOMESERVER_IP · Forward Port 4380 · Block Common Exploits on · Websockets Support off."
step "SSL: pick the existing *.example.com certificate · Force SSL on · HTTP/2 Support on."
step "Advanced: leave empty (the app tells nginx not to buffer its event stream itself). Save."
pause
code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "$ORIGIN/health" || true)
if [[ "$code" == "502" || "$code" == "503" || "$code" == "504" ]]; then
  say "${GREEN}✓${RESET} $ORIGIN answers $code: the proxy host is up and waiting for the app (not deployed yet)."
elif [[ "$code" == "200" ]]; then
  say "${GREEN}✓${RESET} $ORIGIN already answers 200."
else
  warn "$ORIGIN answered '$code'. Check the proxy host before going on (DNS, certificate, port 4380)."
  confirm "Continue anyway?" || exit 1
fi

# ─── 6 ────────────────────────────────────────────────────────────────────
stage "Copy the data: your Home moves to the homeserver"
say "From $LOCAL_DATA to $HOMESERVER:/docker/settle/data. Both sides are uid 1000, so no chown."
say "The container starts on this folder and migrates the database itself."
du -sh "$LOCAL_DATA" 2>/dev/null | sed 's/^/    /'
ls -la "$LOCAL_DATA" 2>/dev/null | sed 's/^/    /'
if hs 'test -e /docker/settle/data/settle.sqlite'; then
  warn "/docker/settle/data/settle.sqlite already exists on the homeserver. rsync would overwrite it."
fi
confirm "Copy now? (the local copy is left untouched)" || { SKIPPED+=("data copy to /docker/settle/data"); pause; }
if [[ ! " ${SKIPPED[*]} " =~ "data copy" ]]; then
  hs 'mkdir -p /docker/settle/data'
  rsync -a --exclude 'server.log' --exclude '*.db' "$LOCAL_DATA/" "$HOMESERVER:/docker/settle/data/"
  hs 'ls -la /docker/settle/data' | sed 's/^/    /'
  say "${GREEN}✓${RESET} copied."
fi
pause

# ─── 7 ────────────────────────────────────────────────────────────────────
stage "Ship it: merge hosting into main and push"
say "The push runs the workflow: check → image → deploy on the homeserver. About five minutes."
git log --oneline main..hosting | sed 's/^/    /'
confirm "Fast-forward main to hosting and push to origin?" || { warn "not pushed; stopping here"; exit 1; }
git checkout -q main && git merge -q --ff-only hosting && git push -q origin main
say "${GREEN}✓${RESET} pushed. Watching the run..."
sleep 8
run_id=$(gh run list --workflow deploy --branch main --limit 1 --json databaseId --jq '.[0].databaseId' || true)
open_url "https://github.com/$REPO/actions"
if [[ -n "$run_id" ]]; then
  gh run watch "$run_id" --exit-status && deployed=1 || deployed=0
else
  warn "could not find the run; watch it in the browser"; deployed=0
fi
if [[ "$deployed" == 1 ]] && curl -fsS --max-time 10 "$ORIGIN/health" >/dev/null; then
  say "${GREEN}✓${RESET} $ORIGIN/health answers. Settle is live on the homeserver."
else
  warn "The run failed or $ORIGIN/health does not answer yet. Read the run's log; the deploy job prints docker compose logs on failure."
  confirm "Continue with the remaining stages anyway?" || exit 1
fi
pause

# ─── 8 ────────────────────────────────────────────────────────────────────
stage "Gatus: one health check"
say "Appends an endpoint to /docker/monitoring/gatus/config.yaml (tracked in the homeserver repo) and restarts Gatus."
SNIPPET=$(cat <<'YAML'

  # Settle (settle.example.com): the home-design app, deployed by its own repo's CI. One check, no
  # SLO, as agreed on 2026-09-19; the app's data and deploy live in alexzfe/settle.
  - name: settle
    group: apps
    url: "https://settle.example.com/health"
    interval: 2m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
        description: "Settle is down (settle.example.com/health)"
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2
YAML
)
printf '%s\n' "$SNIPPET" | sed 's/^/    /'
if hs 'grep -q "^  - name: settle$" /docker/monitoring/gatus/config.yaml'; then
  say "${GREEN}✓${RESET} already there."
elif confirm "Append it and restart Gatus?"; then
  printf '%s\n' "$SNIPPET" | hs 'cat >> /docker/monitoring/gatus/config.yaml && cd /docker/monitoring && docker compose restart gatus' | sed 's/^/    /'
  say "${GREEN}✓${RESET} appended and restarted."
  open_url "http://$HOMESERVER_IP:8085"
  step "Check that the apps → settle check turns green."
else
  SKIPPED+=("Gatus check for settle.example.com/health")
fi
pause

# ─── 9 ────────────────────────────────────────────────────────────────────
stage "Point your Home Folder at the homeserver"
say "Runs the same command the About page now shows, inside $HOME_FOLDER."
say "It rewrites .mcp.json to $ORIGIN and .claude/settings.json to the GitHub marketplace,"
say "keeping the old files as *.before-settle. On this desktop the local checkout stays registered as the"
say "marketplace, so Skills keep coming from the source tree; on the laptop, run the install line it prints."
CMD="curl -fsSL \"$ORIGIN/api/home_folder_script?home=$HOME_SLUG\" | sh"
say "    (cd $HOME_FOLDER && $CMD)"
if confirm "Run it?"; then
  (cd "$HOME_FOLDER" && sh -c "$CMD") | sed 's/^/    /'
else
  SKIPPED+=("re-point $HOME_FOLDER: cd there and run: $CMD")
fi
open_url "$ORIGIN"
step "Check the Home is there with its Rooms and Decisions."
step "In a terminal: cd $HOME_FOLDER && claude, then /mcp: settle should be connected over $ORIGIN."
step "On your phone, open $ORIGIN → Shopping → a Purchase → Phone page."
pause "Press Enter when you have looked."

finish
say "Local data stays in $LOCAL_DATA; delete it when you trust the copy. For development, run"
say "pnpm dev with SETTLE_DATA_DIR pointing at a scratch folder so the two never mix."
